### ISSUE TITLE
request for adding zh_TW

### ISSUE THREAD

**Issue by i3vi3** [darksmo/jquery-localization-tool#17]
Hi, I'd like to request for adding traditional Chinese used in Taiwan: zh_TW
language name in English: Traditional Chinese
country name in English: Taiwan
translated language name: 繁體中文
translated country name: 臺灣

Relatedly, I'd also like to request for changing (or having an option for changing)
the language name for zh_CN as:
Chinese -> Simplified Chinese,
中文 -> 简体中文.

**Comment by darksmo** [comment]
Done! see v0.0.17 (also you should see zh_TW on darksmo.github.io/jquery-localization-tool/ down in the languages list).
