### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by ghost** [darksmo/jquery-localization-tool#21]
Hi,

It looks great... but I cannot make it working !

I have simply download the ZIP on the web page and also the one from GitHub.
I have try the web pages in demo... but they don't work... I don't see any "dropdown" for the language choice :!

Can you help please ?

Thanks

**Comment by darksmo** [comment]
The index.html file in the demo folder must be deployed on a web server along with other assets. That is, To see the web pages in the demo directory working you need to run a web server that serves the content of the zip archive at the root ("/") path. Then you need to open the browser and navigate to the /demo/index.html url. For example, if you have python and linux installed, one simple way to do this is to open a terminal then:

   cd <zip archive content directory>
   python -m SimpleHTTPServer

then navigate with a browser to http://localhost:8000 .

Also you can start from scratch with a blank file and type html yourself (or copy paste it) along the lines of https://github.com/darksmo/jquery-localization-tool/blob/master/demo/index.html . Of course you would need to update all absolute urls with urls like file:// or relative paths.

**Comment by darksmo** [comment]
Closing this one, it's been a while. Please reopen if relevant...
