### ISSUE TITLE
Set Language based upon URL hash?

### ISSUE THREAD

**Issue by vip3rousmango** [darksmo/jquery-localization-tool#26]
Is there a simple way to set a language based upon a hash (like #en or #fr) inside a URL?

So the user enters: http://website.com/#fr which selects french automatically so the page loads french translation?

**Comment by darksmo** [comment]
It's not built in this widget. But you could first extract the language from the url and then call the translate method.

**Comment by vip3rousmango** [comment]
Gotcha, so would something like this do it? I'm not able to get it working, is there an example of using onLanguageSelected function?.
`        //check if hash tag exists
    if(window.location.hash) {
        var hash_value = window.location.hash.replace('#', '');
        console.log(hash_value);
        if (hash_value === "ca_FR") {
            var onLanguageSelected = function(hash_value) {
                return true;
            }
        }
    }`

**Comment by vip3rousmango** [comment]
Thank you for the tip!

I'm able to extract the hash value from the URL, but am I passing that value to the translate method when I call it?

Or am I using the value to set the 'onLanguageSelected' function under options?

Any insight is appreciated!

**Comment by darksmo** [comment]
Please see the bottom of https://github.com/darksmo/jquery-localization-tool/blob/master/demo/multi-page-localization/index.html . You need to call the translate method with the language.

**Comment by vip3rousmango** [comment]
Ahh missed that one! Got it working, thanks for the help.

**Comment by vip3rousmango** [comment]
Ahh missed that one! Got it working, thanks for the help.
