### ISSUE TITLE
Translate to Danish

### ISSUE THREAD

**Issue by JanCoyle** [darksmo/jquery-localization-tool#5]
Hi

I would like to help to translate your tool to Danish.

Best regards Jan

**Comment by darksmo** [comment]
Hi @JanCoyle ! thanks for offering your help. I've added Danish in the development version (which you can check out and use already). But I'd like to release the next version as well. So could you check that Danmark (Dansk) reads correct to you and the flag looks good down the list of languages in the demo page? http://darksmo.github.io/jquery-localization-tool/  . Many thanks!

**Comment by JanCoyle** [comment]
Thanks Darksmo
I have testet it, and DK works fine - Thank you.
Is there a possibility to auto-detect the browsers language as default, right now it always started with English as default.

**Comment by darksmo** [comment]
Not built in the plugin at the moment. But you can set the default language during the initialization of the plugin. See https://github.com/darksmo/jquery-localization-tool/blob/master/demo/index.html for a sample usage, there is that "defaultLanguage" option that you can pass during initialization. When you translate the strings, you should provide the translation in languages other than the default language.

**Comment by JanCoyle** [comment]
Hi
I have found a script to get the Browsers language+country, but how do I set this at load time ?

<script type="text/javascript">
userLang = navigator.languages ? navigator.languages[0] : (navigator.language || navigator.userLanguage);
alert("The language is: " + userLang);
</script>

**Comment by darksmo** [comment]
The first thing to do **before initializing localizationTool** is to have the user `language_COUNTRY` in a format that is recognized by the localization tool plugin (e.g., en-GB should be en_GB):

   userLang = navigator.languages ? navigator.languages[0] : (navigator.language || navigator.userLanguage);
   userLangPluginFriendly = userLang.replace('-','_');

**then** you can initialize the plugin with `userLangPluginFriendly` as defaultLanguage:

   $('#selectLanguageDropdown').localizationTool({
                'defaultLanguage' : userLangPluginFriendly,
                .... other options ...
   });

**Comment by JanCoyle** [comment]
I think there is an error with defaultLanguge option, because even if i set i static it lock the whole list for en_GB, and nothing else is selectable.

This dosn't work...
$("#widget").localizationTool({
            strings: {
                "defaultLanguage" : "da_DK",
                "id:hello" : {
                    it_IT : "Ciao",
                    de_DE : "Hallo",
                    fr_FR : "Salut",
                    da_DK : "Hej"
                }
            }
        });

**Comment by darksmo** [comment]
This is looking very good to me: http://pastebin.com/Hg6yNS3W

**Comment by JanCoyle** [comment]
Hi... and thanks for feedback.

I had set the defaultLanguage the wrong place sorry... so now the list works again and is default languge i seleted.

The problem is now, that it's not taken the default language from the String, only from the DIV tag, so when using dynamic defaultLangage as mention above and you set:

<div id="hello">UNDEFINED</div>

Then default language is always UNDEFINED.

**Comment by darksmo** [comment]
Sorry I don't understand. It's really hard to help without a complete code example. Can you post a complete example as I did? A jsFiddle with your code would be nice: http://jsfiddle.net/

**Comment by JanCoyle** [comment]
Hi...
I try i link External Resources to GITHUB, but it dosn't work, but my code is here:
http://jsfiddle.net/janborup/vpx8y9yp/

**Comment by darksmo** [comment]
I see... and it's expected. The content of the markup in fact is used as the initial language for the translation. The idea is that you just provide the translations in languages **other than the default one**, and indicate the plugin what is the default language.

**Comment by darksmo** [comment]
Because Danish is now there, I'm going to close this issue. I think this is more like a feature request than a bug, so I'm going to open another issue.

**Comment by darksmo** [comment]
Have created this: https://github.com/darksmo/jquery-localization-tool/issues/7
