### ISSUE TITLE
Adding language Esperanto

### ISSUE THREAD

**Issue by batisteo** [darksmo/jquery-localization-tool#6]
It would be fantastic if you would concider adding Esperanto language!

Here the data, I know it's a particular language.

1. language code: eo
1. country code: none if possible, XX if necessary (eo_XX)
1. language name in English: Esperanto
1. country name in English: none if possible, else Esperantoland
1. translated language name: Esperanto
1. translated country name: none if possible, else Esperantio

**Comment by batisteo** [comment]
![flags](https://cloud.githubusercontent.com/assets/2727048/5964848/bdfae69e-a7f7-11e4-9cdd-53a335359db2.png)

In case you need it.

**Comment by LaPingvino** [comment]
Fixed now, can be closed.
